kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spire:agent
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: spire
roleRef:
  kind: ClusterRole
  name: spire:agent
  apiGroup: rbac.authorization.k8s.io
