apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
patchesStrategicMerge:
  - server.ca.secret.yaml
  - server.tls.secret.yaml
  - server.validatingwebhookconfiguration.yaml
