kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fabric:control
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "endpoints"
    verbs:
      - "get"
      - "list"
      - "watch"
