apiVersion: v1
kind: Service
metadata:
  name: registrar
  namespace: spire
spec:
  ports:
    - name: registrar
      protocol: TCP
      port: 8444
      targetPort: registrar
  selector:
    app: server
