apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: server
  namespace: spire
subjects:
  - kind: ServiceAccount
    name: server
    namespace: spire
roleRef:
  kind: Role
  name: server
  apiGroup: rbac.authorization.k8s.io
