apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spire:server
subjects:
  - kind: ServiceAccount
    name: server
    namespace: spire
roleRef:
  kind: ClusterRole
  name: spire:server
  apiGroup: rbac.authorization.k8s.io
